plugins {
    id 'com.android.library'
    id 'maven-publish'
}
group = 'com.broombots.sweep'
version = '0.8.0'

android {
    namespace = 'com.broombots.sweep'
    compileSdkVersion 30

    defaultConfig {
        minSdkVersion 24
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 28
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    publishing {
        singleVariant("release"){
            withSourcesJar()
        }
    }
}

apply from: '../build.dependencies.gradle'

dependencies {
    implementation("org.ejml:ejml-all:0.44.0")
    testImplementation("junit:junit:4.13.2")

}
afterEvaluate {
    publishing {
        publications {
            gpr(MavenPublication) {
                from components.release
                artifactId = 'SWEEP-core'
            }
        }
        repositories {
            maven {
                name = "GitHubPackages"
                url = uri("https://maven.pkg.github.com/FTC-21430/SWEEPDevelopment")
                credentials {
                    username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
                    password = project.findProperty("gpr.key") ?: System.getenv("GITHUB_TOKEN")
                }
            }
        }
    }
}
